source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'annotate'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'rspec-rails'
  gem 'jasmine-core', github: 'pivotal/jasmine'
  gem 'jasmine', github: 'pivotal/jasmine-gem'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'faker'
  gem 'database_cleaner'
end

gem 'backbone-on-rails'
